-- TEMPORARY FIX: Disable RLS on articles table for testing
-- Run this in your Supabase SQL Editor

-- Disable RLS temporarily
ALTER TABLE articles DISABLE ROW LEVEL SECURITY;

-- Optional: Create proper RLS policies (run after testing)
-- 
-- Re-enable RLS
-- ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
-- 
-- Create policy for service role to insert articles
-- CREATE POLICY "Service role can insert articles" ON articles
--   FOR INSERT
--   TO service_role
--   WITH CHECK (true);
-- 
-- Create policy for service role to update articles  
-- CREATE POLICY "Service role can update articles" ON articles
--   FOR UPDATE
--   TO service_role
--   USING (true);
-- 
-- Create policy for service role to delete articles
-- CREATE POLICY "Service role can delete articles" ON articles
--   FOR DELETE
--   TO service_role
--   USING (true);
-- 
-- Create policy for anonymous users to read published articles
-- CREATE POLICY "Anyone can read published articles" ON articles
--   FOR SELECT
--   TO anon
--   USING (status = 'published');
